version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking_service
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - laravel

  db:
    image: postgres:16
    container_name: booking_db
    restart: always
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: booking_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel

volumes:
  db_data:
  redis_data:

networks:
  laravel:
